# Generated by Django 2.2.16 on 2021-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0008_auto_20210319_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataepidemiologiaerror',
            options={'verbose_name': 'Error de procesamiento de archivo (Epidemiología)', 'verbose_name_plural': 'Errores de procesamiento de archivo (Epidemiología)'},
        ),
        migrations.AlterModelOptions(
            name='datahigieneerror',
            options={'verbose_name': 'Error de procesamiento de archivo (Higiene)', 'verbose_name_plural': 'Errores de procesamiento de archivo (Higiene)'},
        ),
        migrations.AlterModelOptions(
            name='placaerrormodel',
            options={'verbose_name': 'Error de procesamiento de la placa', 'verbose_name_plural': 'Errores de procesamiento de las placas'},
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='msg',
            field=models.TextField(verbose_name='Causa'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='msg',
            field=models.TextField(verbose_name='Causa'),
        ),
        migrations.AlterField(
            model_name='placaerrormodel',
            name='msg',
            field=models.TextField(verbose_name='Causa'),
        ),
    ]
