# Generated by Django 2.2.16 on 2021-04-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0015_auto_20210407_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataepidemiologiaerror',
            options={'ordering': ['pk'], 'verbose_name': 'Error de procesamiento de archivo             de restauración de resultados', 'verbose_name_plural': 'Error de procesamiento de archivos             de restauración de resultados'},
        ),
        migrations.AlterModelOptions(
            name='datahigieneerror',
            options={'ordering': ['pk'], 'verbose_name': 'Error de procesamiento de archivo de muestra', 'verbose_name_plural': 'Errores de procesamiento de archivo de muestras'},
        ),
        migrations.AlterModelOptions(
            name='placaerrormodel',
            options={'ordering': ['pk'], 'verbose_name': 'Error de procesamiento de archivo de resultados', 'verbose_name_plural': 'Errores de procesamiento de             archivos de resultados'},
        ),
    ]
